# Welcome to Sonic Pi v3.1
charizard = "C:/Users/miguel_gallardo/Documents/Audacity/Charizard.wav"
trainer_red_notes = [:Eb3, :G3,:Bb3, :E3, :B3]
index = 0
use_bpm 195
with_fx :reverb do
  use_synth :prophet
  sample charizard
  sleep 17.54
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 2
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 2
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 2
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 1
  play :D4
  play :B3
  play :E3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 1.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 1.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 1.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :B4
  play :Eb4
  play :Bb3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 1.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 1.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 1.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :B4
  play :Eb4
  play :B3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 1.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 1.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 1.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Db5
  play :Eb4
  play :B3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Bb4
  play :Eb4
  play :Bb3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :B4
  play :Eb4
  play :B3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Bb4
  play :Eb4
  play :Bb3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :D4
  play :B3
  play :D3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Bb4
  play :Eb4
  play :Bb3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :B4
  play :Eb4
  play :B3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Bb4
  play :Eb4
  play :Bb3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :F4
  play :Eb4
  play :Ab3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Bb4
  play :Eb4
  play :Bb3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :B4
  play :Eb4
  play :B3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Bb4
  play :Eb4
  play :Bb3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :D4
  play :B3
  play :D3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Bb4
  play :Eb4
  play :Bb3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :B4
  play :Eb4
  play :Bb3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :C5
  play :Gb4
  play :B3
  sleep 1
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 0.5
  play :Db5
  play :Gb4
  play :Db4
  sleep 1
  play :Eb5
  play :Bb4
  play :Eb4
  sleep 2
  play :Eb4
  play :Bb3
  play :Eb3
  sleep 2
  play :E5
  play :B4
  play :B3
  sleep 1
  play :G3
  sleep 0.5
  play :B3
  sleep 0.5
  play :Eb5
  play :Gb3
  sleep 0.5
  play :Bb3
  sleep 0.5
  play :Bb4
  play :F3
  sleep 0.25
  play :B4
  sleep 0.25
  play :C5
  play :A3
  sleep 0.25
  play :Db5
  sleep 0.25
  live_loop :repeat do
    6.times do
      play :Eb5
      play :Eb4
      play :Eb3
      sleep 0.5
      play :Bb4
      play :B3
      sleep 0.5
      play :Eb4
      play :Eb3
      sleep 0.5
      play :Bb4
      play :Gb4
      play :B3
      sleep 0.5
      play :Bb4
      play :Gb4
      play :Eb3
      sleep 0.5
      play :F4
      play :B3
      sleep 0.5
      play :Gb3
      play :G2
      play :E3
      sleep 0.5
      play :F3
      play :D3
      play :B3
      sleep 0.5
      play :Db5
      play :Gb4
      play :Eb3
      sleep 0.5
      play :Bb4
      play :B3
      sleep 0.5
      play :C5
      play :A2
      play :Eb3
      sleep 0.5
      play :A4
      play :B3
      sleep 0.5
      play :B4
      play :E4
      play :Eb3
      sleep 0.5
      play :Ab4
      play :B3
      sleep 0.5
      play :Bb4
      play :Eb4
      play :Eb3
      sleep 0.5
      play :G4
      play :B3
      sleep 0.5
      play :B4
      play :E4
      play :E3
      sleep 0.5
      play :E4
      play :B3
      sleep 0.5
      play :Gb4
      play :Eb3
      sleep 0.5
      play :B3
      sleep 0.5
      play :E5
      play :E4
      play :Eb3
      sleep 0.5
      play :E4
      play :B3
      sleep 0.5
      play :Ab4
      play :Eb3
      sleep 0.5
      play :B3
      sleep 0.5
      play :Ab4
      play :E4
      play :E3
      sleep 0.5
      play :Ab4
      play :E4
      play :B3
      sleep 0.5
      play :Bb4
      play :A4
      play :E3
      sleep 0.5
      play :C4
      sleep 0.5
      play :Gs4
      play :E4
      play :A3
      sleep 0.5
      play :Gs4
      play :E4
      play :B3
      sleep 0.5
      play :Db5
      play :B4
      play :G3
      sleep 0.5
      play :A3
      sleep 0.5
      play :Eb5
      play :Eb4
      play :Eb3
      sleep 0.5
      play :Bb4
      play :B3
      sleep 0.5
      play :Eb4
      play :Eb3
      sleep 0.5
      play :Bb4
      play :Gb4
      play :B3
      sleep 0.5
      play :Bb4
      play :Gb4
      play :Eb3
      sleep 0.5
      play :F4
      play :B3
      sleep 0.5
      play :Gb3
      play :G2
      play :E3
      sleep 0.5
      play :F3
      play :D3
      play :B3
      sleep 0.5
      play :Db5
      play :Gb4
      play :Eb3
      sleep 0.5
      play :Bb4
      play :B3
      sleep 0.5
      play :C5
      play :A2
      play :Eb3
      sleep 0.5
      play :A4
      play :B3
      sleep 0.5
      play :B4
      play :E4
      play :Eb3
      sleep 0.5
      play :Ab4
      play :B3
      sleep 0.5
      play :Bb4
      play :Eb4
      play :Eb3
      sleep 0.5
      play :B4
      play :G4
      play :B3
      sleep 0.5
      play :E5
      play :E4
      play :E3
      sleep 0.5
      play :E4
      play :B3
      sleep 0.5
      play :Gb4
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :A5
      play :E4
      play :E3
      sleep 0.5
      play :E4
      play :B3
      sleep 0.5
      play :Ab4
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :E5
      play :E4
      play :E3
      sleep 0.5
      play :E4
      play :B3
      sleep 0.5
      play :B4
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :B5
      play :E4
      play :E3
      sleep 0.5
      play :E4
      play :B3
      sleep 0.5
      play :Eb5
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :Eb3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :G3
      sleep 0.5
      play :Eb3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :G3
      sleep 0.5
      play :Eb3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :D4
      sleep 0.5
      play :Db4
      sleep 0.5
      play :Eb5
      play :Bb4
      play :C4
      sleep 0.5
      play :B3
      play :Eb3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :E3
      sleep 0.5
      play :Eb3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :E3
      sleep 0.5
      play :E5
      play :B4
      play :Eb3
      sleep 1
      play :D4
      sleep 0.5
      play :Eb5
      play :Ab4
      play :D4
      sleep 0.5
      play :C4
      sleep 0.5
      play :Eb5
      play :Bb4
      play :B3
      play :Eb3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :G3
      sleep 0.5
      play :Eb3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :G3
      sleep 0.5
      play :Eb3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :D4
      sleep 0.5
      play :D4
      sleep 0.5
      play :Eb5
      play :Bb4
      play :C4
      sleep 0.5
      play :Eb3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :B3
      sleep 0.5
      play :Eb3
      sleep 0.5
      play :Eb5
      play :Bb4
      play :B3
      sleep 0.5
      play :G5
      play :D5
      play :Eb3
      sleep 0.5
      play :D4
      sleep 0.5
      play :G5
      play :D5
      play :Db4
      sleep 0.5
      play :C4
      sleep 0.5
      play :Eb5
      play :Bb4
      play :B3
      sleep 2
      play :E4
      play :B3
      play :Eb3
      sleep 2
      play :Db5
      play :Gb4
      play :B3
      sleep 2
      play :D4
      play :G3
      play :Eb3
      sleep 2
      16.times do
        index = 0
        print index
        play trainer_red_notes [index]
        sleep 0.5
        index = index + 1
        play trainer_red_notes [index]
        sleep 0.5
        print index
      end
      play :E6
      play :G5
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :D6
      play :F5
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :Db6
      play :E5
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :C6
      play :Eb4
      play :E3
      sleep 0.5
      play :E4
      sleep 0.5
      play :Eb6
      play :D5
      play :E3
      sleep 0.5
      play :D6
      play :B3
      sleep 0.5
      play :Db6
      play :Db5
      play :Eb4
      sleep 0.5
      play :C6
      play :E4
      sleep 0.5
      play :B5
      play :G5
      play :G4
      sleep 0.5
      play :B3
      sleep 0.5
      play :B5
      play :G5
      play :Eb5
      sleep 0.5
      play :E4
      sleep 0.5
      play :E6
      play :G5
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :D6
      play :F5
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :Db6
      play :E5
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :C6
      play :Eb4
      play :E3
      sleep 0.5
      play :E4
      sleep 0.5
      play :Fb6
      play :G5
      play :E3
      sleep 0.5
      play :E6
      play :A5
      play :B3
      sleep 0.5
      play :Eb6
      play :Eb5
      play :E3
      sleep 0.5
      play :D6
      play :E5
      play :B3
      sleep 0.5
      play :C6
      play :A3
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      play :C6
      play :A3
      play :E3
      sleep 0.5
      play :B3
      sleep 0.5
      4.times do
        index = 3
        print index
        play trainer_red_notes [index]
        sleep 0.5
        index = index + 1
        play trainer_red_notes [index]
        sleep 0.5
        print index
      end
      play :Gb4
      play :Eb3
      sleep 0.5
      play :Bb3
      sleep 0.5
      play :B3
      sleep 0.5
      play :E4
      sleep 0.5
      play :E4
      play :Eb3
      sleep 0.5
      play :E4
      play :Eb3
      sleep 0.5
      5.times do
        index = 0
        print index
        play trainer_red_notes [index]
        sleep 0.5
        index = index + 2
        play trainer_red_notes [index]
        sleep 0.5
        print index
      end
      play :D4
      sleep 0.5
      play :E4
      sleep 0.5
      play :E3
      sleep 0.5
      play :E3
      sleep 0.5
      play :E4
      play :B3
      play :Eb3
      sleep 0.5
      play :E4
      play :B3
      play :A3
      sleep 0.5
      play :Bb4
      play :E4
      play :Eb3
      sleep 0.5
      play :A3
      sleep 0.5
      play :E4
      play :B3
      play :Eb3
      sleep 0.5
      play :E4
      play :B3
      play :A3
      sleep 0.5
      play :B3
      play :E4
      play :Eb3
      sleep 0.5
      play :A3
      sleep 0.5
      play :E4
      play :Bb3
      play :Eb3
      sleep 0.5
      play :E4
      play :Bb3
      play :A3
      sleep 0.5
      play :Bb4
      play :E4
      play :Eb3
      sleep 0.5
      play :A3
      sleep 0.5
      play :E4
      play :Bb3
      play :Eb3
      sleep 0.5
      play :E4
      play :Bb3
      play :A3
      sleep 0.5
      play :A4
      play :E4
      play :Eb3
      sleep 0.5
      play :A3
      sleep 0.5
      play :E4
      play :Bb3
      play :Eb3
      sleep 0.5
      play :E4
      play :Bb3
      play :A3
      sleep 0.5
      play :Bb4
      play :E4
      play :Eb3
      sleep 0.5
      play :A3
      sleep 0.5
      play :E4
      play :B4
      play :Eb3
      sleep 0.5
      play :E4
      play :B4
      play :A3
      sleep 0.5
      play :B4
      play :E4
      play :Eb3
      sleep 0.5
      play :A3
      sleep 0.5
      play :E4
      play :C4
      play :Eb3
      sleep 0.5
      play :E4
      play :C4
      play :B3
      sleep 0.5
      play :Db5
      play :Gb4
      play :Eb3
      sleep 0.5
      play :B3
      sleep 0.5
      play :E4
      play :C4
      play :Eb3
      sleep 0.5
      play :E4
      play :C4
      play :B3
      sleep 0.5
      play :D5
      play :Ab3
      play :B3
      sleep 0.5
      play :Bb3
      sleep 0.5
      play :Eb5
      play :E4
      play :Eb3
      sleep 0.5
      play :E4
      play :B3
      sleep 0.5
      play :Bb4
      play :D4
      sleep 0.5
      play :E4
      sleep 0.5
      play :E5
      play :E4
      play :Eb3
      sleep 0.5
      play :EB4
      play :B3
      sleep 0.5
      play :Bb4
      play :D4
      sleep 0.5
      play :E4
      sleep 0.5
      play :G5
      play :E4
      play :Eb3
      sleep 0.5
      play :E4
      play :B3
      sleep 0.5
      play :Db5
      play :D4
      sleep 0.5
      play :E4
      sleep 0.5
      play :E5
      play :E4
      play :Eb3
      sleep 0.5
      play :EB4
      play :B3
      sleep 0.5
      play :Bb4
      play :D4
      sleep 0.5
      play :E4
      sleep 0.5
      play :Eb5
      play :E4
      play :Eb3
      sleep 0.5
      play :E4
      play :B3
      sleep 0.5
      play :Bb4
      play :D4
      sleep 0.5
      play :E4
      sleep 0.5
      play :E5
      play :E4
      play :Eb3
      sleep 0.5
      play :EB4
      play :B3
      sleep 0.5
      play :Bb4
      play :D4
      sleep 0.5
      play :E4
      sleep 0.5
      play :G5
      play :E4
      play :Eb3
      sleep 0.5
      play :E4
      sleep 0.5
      play :D4
      play :Db5
      sleep 0.5
      play :E4
      sleep 0.5
      play :A5
      play :E4
      play :D4
      sleep 0.5
      play :E4
      play :B3
      sleep 0.5
      play :D5
      play :Bb3
      sleep 0.5
      play :A3
      sleep 0.5
    end
  end
end
